### ISSUE TITLE
World_list

### ISSUE THREAD

**Issue by lokka30** [lokka30/PhantomCombat#43]
```
# Should world list be a BLACKLIST or WHITELIST
# BLACKLIST = Worlds in the list won't be affected
# WHITELIST = Only worlds in the list will be affected
world-list:
 enabled: true
 world-list-mode: 'BLACKLIST'
 world-list:
   - 'BlacklistedWorld'
```
