### ISSUE TITLE
[v2] Armor items bound to 'material groups'

### ISSUE THREAD

**Issue by lokka30** [lokka30/PhantomCombat#60]
Armor items should be able to be bound to material groups into the configuration, for example:
```
armor-types:
  list: ['diamond', 'iron', 'gold', 'chainmail', 'leather', 'elytra', 'turtle']
  diamond:
    soundIds:
      equip-and-unequip: ITEM_ARMOR_EQUIP_DIAMOND
      hit: ENTITY_ZOMBIE_ATTACK_IRON_DOOR
   items:
     - DIAMOND_HELMET
     - DIAMOND_CHESTPLATE
     ...
```
